name: Prepare release branch

on:
  workflow_dispatch:
    inputs:
      major:
        description: Major version number
        required: true
        type: string
      minor:
        description: Minor version number
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  make-release-branch:
    permissions:
      id-token: write # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: "Create release branch"
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release-${{ inputs.major }}.${{ inputs.minor }}.x
          sha: '${{ github.event.pull_request.base.sha }}'

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: test-rust-action-automation
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Setup git"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: "cargo-changelog generate"
        run: nix --extra-experimental-features "nix-command flakes" develop -c "cargo changelog generate custom ${{ inputs.major }}.${{ inputs.minor }}.0"

      - name: "Commit changelog generation"
        run: |
          git add .changelogs
          git commit -sm "Generate changelog for ${{ inputs.major }}.${{ inputs.minor }}.0"

      - name: "cargo-changelog release"
        run: nix --extra-experimental-features "nix-command flakes" develop -c "cargo changelog release"

      - name: "Commit changelog release"
        run: |
          git add .changelogs
          git add CHANGELOG.md
          git commit -sm "Release changelog for ${{ inputs.major }}.${{ inputs.minor }}.0"

      - uses: peter-evans/create-pull-request
        with:
          draft: true
          branch: release-${{ inputs.major }}.${{ inputs.minor }}.0-changelog
          base: release-${{ inputs.major }}.${{ inputs.minor }}.x
          title: "Changelog for ${{ inputs.major }}.${{ inputs.minor }}.0"
          body: |
            This PR contains the consolidated changelog for version ${{ inputs.major }}.${{ inputs.minor }}.0

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

